# Generated by Django 5.2.6 on 2025-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='year_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
