# Generated by Django 5.2.6 on 2025-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.CharField(choices=[('CCS', 'College of Computer Studies'), ('CMBA', 'College of Management, Business, and Accountancy'), ('CCJ', 'College of Criminal Justice'), ('CNAHS', 'College of Nursing and Allied Health Sciences'), ('CEA', 'College of Engineering and Architecture'), ('CASE', 'College of Arts, Sciences and Education')], default='CCS', max_length=50),
        ),
    ]
