# Generated by Django 5.2.6 on 2025-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Class', 'Class'), ('Out of work', 'Out of work'), ('Available', 'Available')], max_length=20),
        ),
    ]
