# Generated by Django 5.2.6 on 2025-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('In Class', 'In Class'), ('Out of Work', 'Out of Work'), ('Available', 'Available')], max_length=20),
        ),
    ]
