# Generated by Django 5.2.7 on 2025-12-09 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schedule_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('BSIT', 'BSIT - Bachelor of Science in Information Technology'), ('BSCS', 'BSCS - Bachelor of Science in Computer Science')], max_length=10)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('BSIT_BSCS', 'BSIT / BSCS'), ('BS_Nursing', 'BS Nursing'), ('BS_CE', 'BS Civil Engineering'), ('BS_Arch', 'BS Architecture'), ('BS_Accountancy', 'BS Accountancy'), ('BS_Psychology', 'BS Psychology'), ('BS_Criminology', 'BS Criminology'), ('BS_Education', 'BS Education'), ('BS_Hospitality', 'BS Hospitality Management'), ('BS_Tourism', 'BS Tourism')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
