"""
Django settings for academeet project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import urlparse
# new
import dj_database_url
from dotenv import load_dotenv
# Load .env only if the project explicitly allows it (prevents automatic use of a production DATABASE_URL
# stored in .env when developing locally). Set USE_ENV_FILE=1 to enable loading the .env file.
if os.environ.get("RENDER", "") != "true":
    # Load .env from the same directory as settings.py
    env_path = Path(__file__).resolve().parent / '.env'
    load_dotenv(env_path)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2&$7vnuba3((b8kpd21!lsh5=&pjuezuib-c$(fe@9mf+w_oxd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in
os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if
h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in
os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if
o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'settings_app',
    'admin_dashboard',
    'core',
    'professor_inline', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
]

# WhiteNoise: serve compressed static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Security (production)
if os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true":
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'academeet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "academeet" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academeet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL (12-factor) when provided, otherwise fall back to local sqlite
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    # Parse the database URL (Postgres, MySQL, etc.) for production environments
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            # Allow disabling SSL enforcement via env in dev if needed
            ssl_require=os.getenv("DB_SSL", "True").lower() in ("1", "true", "yes"),
        )
    }
else:
    # Simple local sqlite database for development (no additional DB drivers required)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "academeet" / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Where to redirect for login-required pages
LOGIN_URL = '/'
# Default redirect after login (can be a URL name)
LOGIN_REDIRECT_URL = '/dashboard/'
#NEW
LOGOUT_REDIRECT_URL = '/'



# Email configuration: prefer environment variables for production; fall back to Gmail SMTP for debugging
import os
 
# Default to the console backend for development so emails are printed to the runserver console.
# You can override via environment variables for production to use SMTP.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# Optional SMTP settings (only used if EMAIL_BACKEND is set to the SMTP backend via env)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'academeet.25@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'ujvnxjjazezhlllw')
# Use the Gmail account as the default sender to avoid DMARC/SPF issues
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)



# ----------------------------------------------------
# 👇 NEW: MEDIA FILE CONFIGURATION (CRITICAL)
# ----------------------------------------------------

# URL prefix for media files served from the MEDIA_ROOT.
# This is how the browser will request the files (e.g., /media/profile_pics/image.jpg)
MEDIA_URL = '/media/'

# Absolute file system path to the directory that will hold user-uploaded files.
# This will create a 'media' folder next to your 'academeet' project folder.
MEDIA_ROOT = BASE_DIR / 'media'