# Generated by Django 5.2.7 on 2025-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_inline', '0002_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office_location',
            field=models.CharField(blank=True, default='TBA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
