# Generated by Django 5.2.7 on 2025-11-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemholiday',
            options={'ordering': ['date'], 'verbose_name': 'System Holiday', 'verbose_name_plural': 'System Holidays'},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'verbose_name': 'Teacher Availability Slot', 'verbose_name_plural': 'Teacher Availability Slots'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_app_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemholiday',
            name='category',
            field=models.CharField(choices=[('FEDERAL', 'Federal Holiday'), ('SCHOOL', 'School Break'), ('OTHER', 'Other Holiday')], default='OTHER', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='systemholiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Holiday Date'),
        ),
        migrations.AlterField(
            model_name='systemholiday',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Holiday Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
