# Generated by Django 5.2.7 on 2025-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_systemholiday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
